### ISSUE TITLE
$element.data('iceParams')

### ISSUE THREAD

**Issue by akousseksou** [EyeCode/jquery-ice#3]
si on change dynamiquement la valeur du data-ice-params, le changement ne sera pas pri en compe par le script, donc je propose de mettre à jour [la ligne 192](https://github.com/EyeCode/jquery-ice/blob/master/jquery-ice/jquery-ice.js#L192) pour utiliser _$element.attr('data-ice-params')_ au lieu de _$element.data('iceParams')_

**Comment by EyeCode** [comment]
Not a bug, that's work as intented, be sure to use $element.data('iceParams', foobar) to set something
